package com.littleGreenMan.Pong_Madness.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.littleGreenMan.Pong_Madness.model.Binome;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BINOME.
*/
public class BinomeDao extends AbstractDao<Binome, Long> {

    public static final String TABLENAME = "BINOME";

    /**
     * Properties of entity Binome.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property DoubleGameId = new Property(2, Long.class, "doubleGameId", false, "DOUBLE_GAME_ID");
    };

    private DaoSession daoSession;

    private Query<Binome> doubleParticipant_DoubleParticipantListQuery;

    public BinomeDao(DaoConfig config) {
        super(config);
    }
    
    public BinomeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BINOME' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'DOUBLE_GAME_ID' INTEGER);"); // 2: doubleGameId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BINOME'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Binome entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    protected void attachEntity(Binome entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Binome readEntity(Cursor cursor, int offset) {
        Binome entity = new Binome( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Binome entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Binome entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Binome entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "doubleParticipantList" to-many relationship of DoubleParticipant. */
    public List<Binome> _queryDoubleParticipant_DoubleParticipantList(Long doubleGameId) {
        synchronized (this) {
            if (doubleParticipant_DoubleParticipantListQuery == null) {
                QueryBuilder<Binome> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DoubleGameId.eq(null));
                doubleParticipant_DoubleParticipantListQuery = queryBuilder.build();
            }
        }
        Query<Binome> query = doubleParticipant_DoubleParticipantListQuery.forCurrentThread();
        query.setParameter(0, doubleGameId);
        return query.list();
    }

}
