package com.littleGreenMan.Pong_Madness.model;

import de.greenrobot.dao.DaoException;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BINOME.
 */
public class Binome {

    private Long id;
    private String name;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BinomeDao myDao;

    private List<PlayerBinome> playerBinomeList;
    private List<DoubleParticipant> doubleParticipantList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Binome() {
    }

    public Binome(Long id) {
        this.id = id;
    }

    public Binome(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBinomeDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<PlayerBinome> getPlayerBinomeList() {
        if (playerBinomeList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlayerBinomeDao targetDao = daoSession.getPlayerBinomeDao();
            List<PlayerBinome> playerBinomeListNew = targetDao._queryBinome_PlayerBinomeList(id);
            synchronized (this) {
                if(playerBinomeList == null) {
                    playerBinomeList = playerBinomeListNew;
                }
            }
        }
        return playerBinomeList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPlayerBinomeList() {
        playerBinomeList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<DoubleParticipant> getDoubleParticipantList() {
        if (doubleParticipantList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DoubleParticipantDao targetDao = daoSession.getDoubleParticipantDao();
            List<DoubleParticipant> doubleParticipantListNew = targetDao._queryBinome_DoubleParticipantList(id);
            synchronized (this) {
                if(doubleParticipantList == null) {
                    doubleParticipantList = doubleParticipantListNew;
                }
            }
        }
        return doubleParticipantList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetDoubleParticipantList() {
        doubleParticipantList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
