package com.littleGreenMan.Pong_Madness.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DOUBLE_GAME.
 */
public class DoubleGame extends Game  {

    private long identifier;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DoubleGame() {
    }

    public DoubleGame(long identifier) {
        this.identifier = identifier;
    }

    public long getIdentifier() {
        return identifier;
    }

    public void setIdentifier(long identifier) {
        this.identifier = identifier;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
