package com.littleGreenMan.Pong_Madness.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DOUBLE_GAME.
 */
public class DoubleGame extends Game  {

    private Long id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DoubleGame() {
    }

    public DoubleGame(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
