package com.littleGreenMan.Pong_Madness.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GAME_TOURNEMENT.
 */
public class GameTournement {

    private Long identifier;
    private Long gameId;
    private Long tournementId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GameTournement() {
    }

    public GameTournement(Long identifier) {
        this.identifier = identifier;
    }

    public GameTournement(Long identifier, Long gameId, Long tournementId) {
        this.identifier = identifier;
        this.gameId = gameId;
        this.tournementId = tournementId;
    }

    public Long getIdentifier() {
        return identifier;
    }

    public void setIdentifier(Long identifier) {
        this.identifier = identifier;
    }

    public Long getGameId() {
        return gameId;
    }

    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    public Long getTournementId() {
        return tournementId;
    }

    public void setTournementId(Long tournementId) {
        this.tournementId = tournementId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
