package com.littleGreenMan.Pong_Madness.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.littleGreenMan.Pong_Madness.model.PlayerTournement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLAYER_TOURNEMENT.
*/
public class PlayerTournementDao extends AbstractDao<PlayerTournement, Long> {

    public static final String TABLENAME = "PLAYER_TOURNEMENT";

    /**
     * Properties of entity PlayerTournement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Identifier = new Property(0, Long.class, "identifier", true, "IDENTIFIER");
        public final static Property PlayerId = new Property(1, Long.class, "playerId", false, "PLAYER_ID");
        public final static Property TournementId = new Property(2, Long.class, "tournementId", false, "TOURNEMENT_ID");
    };

    private DaoSession daoSession;

    private Query<PlayerTournement> player_PlayerTournementListQuery;
    private Query<PlayerTournement> tournement_PlayerTournementListQuery;

    public PlayerTournementDao(DaoConfig config) {
        super(config);
    }
    
    public PlayerTournementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLAYER_TOURNEMENT' (" + //
                "'IDENTIFIER' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: identifier
                "'PLAYER_ID' INTEGER," + // 1: playerId
                "'TOURNEMENT_ID' INTEGER);"); // 2: tournementId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLAYER_TOURNEMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PlayerTournement entity) {
        stmt.clearBindings();
 
        Long identifier = entity.getIdentifier();
        if (identifier != null) {
            stmt.bindLong(1, identifier);
        }
 
        Long playerId = entity.getPlayerId();
        if (playerId != null) {
            stmt.bindLong(2, playerId);
        }
 
        Long tournementId = entity.getTournementId();
        if (tournementId != null) {
            stmt.bindLong(3, tournementId);
        }
    }

    @Override
    protected void attachEntity(PlayerTournement entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PlayerTournement readEntity(Cursor cursor, int offset) {
        PlayerTournement entity = new PlayerTournement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // identifier
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // playerId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // tournementId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PlayerTournement entity, int offset) {
        entity.setIdentifier(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlayerId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTournementId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PlayerTournement entity, long rowId) {
        entity.setIdentifier(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PlayerTournement entity) {
        if(entity != null) {
            return entity.getIdentifier();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "playerTournementList" to-many relationship of Player. */
    public List<PlayerTournement> _queryPlayer_PlayerTournementList(Long playerId) {
        synchronized (this) {
            if (player_PlayerTournementListQuery == null) {
                QueryBuilder<PlayerTournement> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PlayerId.eq(null));
                player_PlayerTournementListQuery = queryBuilder.build();
            }
        }
        Query<PlayerTournement> query = player_PlayerTournementListQuery.forCurrentThread();
        query.setParameter(0, playerId);
        return query.list();
    }

    /** Internal query to resolve the "playerTournementList" to-many relationship of Tournement. */
    public List<PlayerTournement> _queryTournement_PlayerTournementList(Long tournementId) {
        synchronized (this) {
            if (tournement_PlayerTournementListQuery == null) {
                QueryBuilder<PlayerTournement> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TournementId.eq(null));
                tournement_PlayerTournementListQuery = queryBuilder.build();
            }
        }
        Query<PlayerTournement> query = tournement_PlayerTournementListQuery.forCurrentThread();
        query.setParameter(0, tournementId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPlayerDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTournementDao().getAllColumns());
            builder.append(" FROM PLAYER_TOURNEMENT T");
            builder.append(" LEFT JOIN PLAYER T0 ON T.'PLAYER_ID'=T0.'IDENTIFIER'");
            builder.append(" LEFT JOIN TOURNEMENT T1 ON T.'TOURNEMENT_ID'=T1.'IDENTIFIER'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PlayerTournement loadCurrentDeep(Cursor cursor, boolean lock) {
        PlayerTournement entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Player player = loadCurrentOther(daoSession.getPlayerDao(), cursor, offset);
        entity.setPlayer(player);
        offset += daoSession.getPlayerDao().getAllColumns().length;

        Tournement tournement = loadCurrentOther(daoSession.getTournementDao(), cursor, offset);
        entity.setTournement(tournement);

        return entity;    
    }

    public PlayerTournement loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PlayerTournement> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PlayerTournement> list = new ArrayList<PlayerTournement>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PlayerTournement> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PlayerTournement> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
