package com.littleGreenMan.Pong_Madness.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PLAYER_BINOME.
 */
public class PlayerBinome {

    private long identifier;
    private Long playerId;
    private Long binomeId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PlayerBinome() {
    }

    public PlayerBinome(long identifier) {
        this.identifier = identifier;
    }

    public PlayerBinome(long identifier, Long playerId, Long binomeId) {
        this.identifier = identifier;
        this.playerId = playerId;
        this.binomeId = binomeId;
    }

    public long getIdentifier() {
        return identifier;
    }

    public void setIdentifier(long identifier) {
        this.identifier = identifier;
    }

    public Long getPlayerId() {
        return playerId;
    }

    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    public Long getBinomeId() {
        return binomeId;
    }

    public void setBinomeId(Long binomeId) {
        this.binomeId = binomeId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
