package com.littleGreenMan.Pong_Madness.model;

import java.util.List;
import com.littleGreenMan.Pong_Madness.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TOURNEMENT.
 */
public class Tournement {

    private long identifier;
    private String name;
    private java.util.Date startDate;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TournementDao myDao;

    private List<PlayerTournement> playerTournementList;
    private List<GameTournement> gameTournementList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Tournement() {
    }

    public Tournement(long identifier) {
        this.identifier = identifier;
    }

    public Tournement(long identifier, String name, java.util.Date startDate) {
        this.identifier = identifier;
        this.name = name;
        this.startDate = startDate;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTournementDao() : null;
    }

    public long getIdentifier() {
        return identifier;
    }

    public void setIdentifier(long identifier) {
        this.identifier = identifier;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getStartDate() {
        return startDate;
    }

    public void setStartDate(java.util.Date startDate) {
        this.startDate = startDate;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<PlayerTournement> getPlayerTournementList() {
        if (playerTournementList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlayerTournementDao targetDao = daoSession.getPlayerTournementDao();
            List<PlayerTournement> playerTournementListNew = targetDao._queryTournement_PlayerTournementList(identifier);
            synchronized (this) {
                if(playerTournementList == null) {
                    playerTournementList = playerTournementListNew;
                }
            }
        }
        return playerTournementList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPlayerTournementList() {
        playerTournementList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<GameTournement> getGameTournementList() {
        if (gameTournementList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            GameTournementDao targetDao = daoSession.getGameTournementDao();
            List<GameTournement> gameTournementListNew = targetDao._queryTournement_GameTournementList(identifier);
            synchronized (this) {
                if(gameTournementList == null) {
                    gameTournementList = gameTournementListNew;
                }
            }
        }
        return gameTournementList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetGameTournementList() {
        gameTournementList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
